/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru.hse.software.construction

import ru.hse.software.construction.CookieKeys.CALORIES_PROPERTY_KEY
import ru.hse.software.construction.CookieKeys.COOKIE_TYPE_PROPERTY_KEY
import ru.hse.software.construction.CookieKeys.WEIGHT_PROPERTY_KEY
import ru.hse.software.construction.fabric.method.Baker
import ru.hse.software.construction.fabric.method.ChocolateCookieBaker
import ru.hse.software.construction.fabric.method.CoconutCookie
import ru.hse.software.construction.flyweight.CampFire

object CookieKeys {
    const val WEIGHT_PROPERTY_KEY = "WEIGHT_PROPERTY_KEY"
    const val CALORIES_PROPERTY_KEY = "CALORIES_PROPERTY_KEY"
    const val COOKIE_TYPE_PROPERTY_KEY = "COOKIE_TYPE_PROPERTY_KEY"
}

fun getCreator(type: CookieType): Baker =
    when (type) {
        CookieType.CHOCOLATE -> ChocolateCookieBaker()
        // Пример использования функционального интерфейса
        CookieType.COCONUT -> Baker { properties ->
            CoconutCookie(
                1.0,
                emptyList(),
                properties[CALORIES_PROPERTY_KEY] as Double
            )
        }
    }

fun main() {
    // Парсим application.yaml и получаем ниже
    val properties = mapOf(
        WEIGHT_PROPERTY_KEY to 10.0,
        CALORIES_PROPERTY_KEY to 20.0,
        COOKIE_TYPE_PROPERTY_KEY to CookieType.CHOCOLATE
    )

    val baker = getCreator(properties[COOKIE_TYPE_PROPERTY_KEY] as CookieType)
    val cookie = baker.createCookie(properties)
    baker.createCookie(mapOf(
        WEIGHT_PROPERTY_KEY to 100.0,
        CALORIES_PROPERTY_KEY to 220.0,
    ))

    println("${cookie.weight} ${cookie.calories} ${cookie.ingredient}")

    CampFire().show(10000000)
}

enum class CookieType {
    CHOCOLATE, COCONUT
}
