spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hse_sc
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver

  cloud:
    openfeign:
      client:
        config:
          cat-facts:
            url: https://cat-fact.herokuapp.com

#  h2:
#    console.enabled: true
